from __future__ import annotations

from typing import Any, Literal

from adeu_arc_agi import derive_v42g2_arc_reasoning_run_record


def derive_v42g2_reasoning_run_record(
    *,
    puzzle_input_bundle: dict[str, Any],
    selected_puzzle_id: str,
    task_packet: dict[str, Any],
    task_packet_ref: str,
    observation_frame: dict[str, Any],
    observation_frame_ref: str,
    hypothesis_frame: dict[str, Any],
    hypothesis_frame_ref: str,
    action_proposal: dict[str, Any],
    action_proposal_ref: str,
    rollout_trace: dict[str, Any] | None,
    rollout_trace_ref: str | None,
    environment_ref: str,
    session_ref: str,
    competition_scope_ref: str,
    model_id: str,
    run_id: str,
    agent_profile_ref: str,
    run_config_ref: str,
    prompt_profile_ref: str | None,
    reasoning_effort_requested: Literal["low", "medium", "high", "xhigh"],
    reasoning_effort_observed: Literal["low", "medium", "high", "xhigh"],
    reasoning_effort_source_kind: Literal["requested_only", "provider_observed"],
    task_packet_emission_evidence_refs: list[str],
    observation_frame_emission_evidence_refs: list[str],
    hypothesis_frame_emission_evidence_refs: list[str],
    action_proposal_emission_evidence_refs: list[str],
    rollout_trace_emission_evidence_refs: list[str],
    emission_sequence_register: list[dict[str, Any]],
    run_execution_status: Literal[
        "started",
        "failed_before_task_packet",
        "task_emitted",
        "observation_emitted",
        "hypothesis_emitted",
        "action_emitted",
        "rollout_emitted",
        "blocked_or_deferred",
        "completed",
    ],
    run_terminal_posture: Literal[
        "completed_with_rollout",
        "completed_without_rollout",
        "blocked_or_deferred",
        "failed",
    ],
    rollout_presence_posture: Literal["rollout_present", "rollout_absent"],
    branching_posture: Literal["no_branching", "branching_observed"],
    branching_visibility_status: Literal["not_applicable", "typed_visible"],
    branch_event_refs: list[str],
    settlement_posture_carry: dict[str, Any],
    run_summary: str,
    evidence_refs: list[str],
) -> dict[str, Any]:
    return derive_v42g2_arc_reasoning_run_record(
        puzzle_input_bundle=puzzle_input_bundle,
        selected_puzzle_id=selected_puzzle_id,
        task_packet=task_packet,
        task_packet_ref=task_packet_ref,
        observation_frame=observation_frame,
        observation_frame_ref=observation_frame_ref,
        hypothesis_frame=hypothesis_frame,
        hypothesis_frame_ref=hypothesis_frame_ref,
        action_proposal=action_proposal,
        action_proposal_ref=action_proposal_ref,
        rollout_trace=rollout_trace,
        rollout_trace_ref=rollout_trace_ref,
        environment_ref=environment_ref,
        session_ref=session_ref,
        competition_scope_ref=competition_scope_ref,
        model_id=model_id,
        run_id=run_id,
        agent_profile_ref=agent_profile_ref,
        run_config_ref=run_config_ref,
        prompt_profile_ref=prompt_profile_ref,
        reasoning_effort_requested=reasoning_effort_requested,
        reasoning_effort_observed=reasoning_effort_observed,
        reasoning_effort_source_kind=reasoning_effort_source_kind,
        task_packet_emission_evidence_refs=task_packet_emission_evidence_refs,
        observation_frame_emission_evidence_refs=observation_frame_emission_evidence_refs,
        hypothesis_frame_emission_evidence_refs=hypothesis_frame_emission_evidence_refs,
        action_proposal_emission_evidence_refs=action_proposal_emission_evidence_refs,
        rollout_trace_emission_evidence_refs=rollout_trace_emission_evidence_refs,
        emission_sequence_register=emission_sequence_register,
        run_execution_status=run_execution_status,
        run_terminal_posture=run_terminal_posture,
        rollout_presence_posture=rollout_presence_posture,
        branching_posture=branching_posture,
        branching_visibility_status=branching_visibility_status,
        branch_event_refs=branch_event_refs,
        settlement_posture_carry=settlement_posture_carry,
        run_summary=run_summary,
        evidence_refs=evidence_refs,
    )
