from __future__ import annotations

from typing import Any, Literal

from adeu_arc_agi import derive_v42e_arc_scorecard_manifest


def derive_v42e_scorecard_manifest(
    *,
    task_packet: dict[str, Any],
    task_packet_ref: str,
    observation_frame: dict[str, Any],
    observation_frame_ref: str,
    hypothesis_frame: dict[str, Any],
    hypothesis_frame_ref: str,
    action_proposal: dict[str, Any],
    action_proposal_ref: str,
    rollout_trace: dict[str, Any],
    rollout_trace_ref: str,
    local_eval_record: dict[str, Any],
    local_eval_record_ref: str,
    environment_ref: str,
    session_ref: str,
    competition_scope_ref: str,
    scorecard_scope: Literal["single_run_scorecard_posture"],
    scorecard_profile: str,
    model_id: str,
    run_id: str,
    scorecard_source_kind: Literal[
        "local_shadow_only",
        "official_imported",
        "competition_posture_declared_no_official_scorecard",
        "deferred_absent",
    ],
    authority_posture: str,
    authority_scope: Literal[
        "local_only",
        "official_imported",
        "competition_posture_only",
        "deferred",
    ],
    authority_source_kind: Literal[
        "local_shadow_only",
        "official_imported",
        "competition_posture_declared_no_official_scorecard",
        "deferred_absent",
    ],
    authority_validity: Literal["valid", "provisional", "deferred"],
    authority_limitations: str,
    competition_mode_posture: Literal[
        "not_applicable",
        "declared_deferred",
        "eligible_but_not_exercised",
        "officially_exercised",
    ],
    local_replay_lineage_refs: list[str],
    external_replay_authority_refs: list[str],
    scorecard_facing_metrics: list[dict[str, Any]],
    official_scorecard_outcome_metrics: list[dict[str, Any]],
    scorecard_outcome_summary: str,
    settlement_posture_carry: dict[str, Any],
    authority_basis_refs: list[str],
    deferred_authority_assertions: list[str],
    evidence_refs: list[str],
) -> dict[str, Any]:
    return derive_v42e_arc_scorecard_manifest(
        task_packet=task_packet,
        task_packet_ref=task_packet_ref,
        observation_frame=observation_frame,
        observation_frame_ref=observation_frame_ref,
        hypothesis_frame=hypothesis_frame,
        hypothesis_frame_ref=hypothesis_frame_ref,
        action_proposal=action_proposal,
        action_proposal_ref=action_proposal_ref,
        rollout_trace=rollout_trace,
        rollout_trace_ref=rollout_trace_ref,
        local_eval_record=local_eval_record,
        local_eval_record_ref=local_eval_record_ref,
        environment_ref=environment_ref,
        session_ref=session_ref,
        competition_scope_ref=competition_scope_ref,
        scorecard_scope=scorecard_scope,
        scorecard_profile=scorecard_profile,
        model_id=model_id,
        run_id=run_id,
        scorecard_source_kind=scorecard_source_kind,
        authority_posture=authority_posture,
        authority_scope=authority_scope,
        authority_source_kind=authority_source_kind,
        authority_validity=authority_validity,
        authority_limitations=authority_limitations,
        competition_mode_posture=competition_mode_posture,
        local_replay_lineage_refs=local_replay_lineage_refs,
        external_replay_authority_refs=external_replay_authority_refs,
        scorecard_facing_metrics=scorecard_facing_metrics,
        official_scorecard_outcome_metrics=official_scorecard_outcome_metrics,
        scorecard_outcome_summary=scorecard_outcome_summary,
        settlement_posture_carry=settlement_posture_carry,
        authority_basis_refs=authority_basis_refs,
        deferred_authority_assertions=deferred_authority_assertions,
        evidence_refs=evidence_refs,
    )
