from __future__ import annotations

from typing import Any, Literal

from adeu_arc_agi import derive_v42f_arc_submission_execution_record


def derive_v42f_submission_execution_record(
    *,
    task_packet: dict[str, Any],
    task_packet_ref: str,
    observation_frame: dict[str, Any],
    observation_frame_ref: str,
    hypothesis_frame: dict[str, Any],
    hypothesis_frame_ref: str,
    action_proposal: dict[str, Any],
    action_proposal_ref: str,
    rollout_trace: dict[str, Any],
    rollout_trace_ref: str,
    local_eval_record: dict[str, Any],
    local_eval_record_ref: str,
    scorecard_manifest: dict[str, Any],
    scorecard_manifest_ref: str,
    environment_ref: str,
    session_ref: str,
    competition_scope_ref: str,
    model_id: str,
    run_id: str,
    submission_authorization_status: Literal["not_authorized", "deferred", "authorized"],
    submission_authorization_source_kind: Literal[
        "local_shadow_only",
        "official_imported",
        "competition_posture_declared_no_official_scorecard",
        "deferred_absent",
    ],
    submission_authorization_validity: Literal["valid", "deferred", "invalid"],
    submission_authorization_basis_refs: list[str],
    submission_execution_status: Literal[
        "not_submitted",
        "submitted_pending_receipt",
        "submitted_acknowledged",
        "submission_failed",
    ],
    submission_transport_profile: str,
    external_request_ref: str,
    submission_payload_ref: str,
    submission_payload_hash: str,
    submission_request_ts: int,
    submission_receipt_ref: str | None,
    submission_receipt_hash: str | None,
    submission_receipt_ts: int | None,
    result_import_status: Literal[
        "not_imported",
        "deferred",
        "official_imported",
        "import_failed",
    ],
    result_source_kind: Literal[
        "local_shadow_only",
        "official_imported",
        "competition_posture_declared_no_official_scorecard",
        "deferred_absent",
    ],
    result_authority_validity: Literal["valid", "deferred", "invalid"],
    result_authority_basis_refs: list[str],
    result_import_ref: str | None,
    result_import_hash: str | None,
    result_import_ts: int | None,
    lifecycle_transition_matrix_ref: str,
    submission_result_posture: str,
    submission_result_summary: str,
    bounded_orchestration_constraint_register: list[
        Literal[
            "deferred_multi_run",
            "no_parallel_competition_fanout",
            "no_tournament_execution",
            "single_submission_only",
        ]
    ],
    settlement_posture_carry: dict[str, Any],
    deferred_authority_assertions: list[str],
    evidence_refs: list[str],
) -> dict[str, Any]:
    return derive_v42f_arc_submission_execution_record(
        task_packet=task_packet,
        task_packet_ref=task_packet_ref,
        observation_frame=observation_frame,
        observation_frame_ref=observation_frame_ref,
        hypothesis_frame=hypothesis_frame,
        hypothesis_frame_ref=hypothesis_frame_ref,
        action_proposal=action_proposal,
        action_proposal_ref=action_proposal_ref,
        rollout_trace=rollout_trace,
        rollout_trace_ref=rollout_trace_ref,
        local_eval_record=local_eval_record,
        local_eval_record_ref=local_eval_record_ref,
        scorecard_manifest=scorecard_manifest,
        scorecard_manifest_ref=scorecard_manifest_ref,
        environment_ref=environment_ref,
        session_ref=session_ref,
        competition_scope_ref=competition_scope_ref,
        model_id=model_id,
        run_id=run_id,
        submission_authorization_status=submission_authorization_status,
        submission_authorization_source_kind=submission_authorization_source_kind,
        submission_authorization_validity=submission_authorization_validity,
        submission_authorization_basis_refs=submission_authorization_basis_refs,
        submission_execution_status=submission_execution_status,
        submission_transport_profile=submission_transport_profile,
        external_request_ref=external_request_ref,
        submission_payload_ref=submission_payload_ref,
        submission_payload_hash=submission_payload_hash,
        submission_request_ts=submission_request_ts,
        submission_receipt_ref=submission_receipt_ref,
        submission_receipt_hash=submission_receipt_hash,
        submission_receipt_ts=submission_receipt_ts,
        result_import_status=result_import_status,
        result_source_kind=result_source_kind,
        result_authority_validity=result_authority_validity,
        result_authority_basis_refs=result_authority_basis_refs,
        result_import_ref=result_import_ref,
        result_import_hash=result_import_hash,
        result_import_ts=result_import_ts,
        lifecycle_transition_matrix_ref=lifecycle_transition_matrix_ref,
        submission_result_posture=submission_result_posture,
        submission_result_summary=submission_result_summary,
        bounded_orchestration_constraint_register=bounded_orchestration_constraint_register,
        settlement_posture_carry=settlement_posture_carry,
        deferred_authority_assertions=deferred_authority_assertions,
        evidence_refs=evidence_refs,
    )
