from __future__ import annotations

from enum import Enum


class ReasonSeverity(str, Enum):
    ERROR = "ERROR"
    WARN = "WARN"
    INFO = "INFO"


class ReasonCode(str, Enum):
    # Schema/shape
    SCHEMA_INVALID = "SCHEMA_INVALID"
    UNSUPPORTED_SCHEMA_VERSION = "UNSUPPORTED_SCHEMA_VERSION"

    # Ambiguity / patching
    AMBIGUITY_OPTION_INVALID = "AMBIGUITY_OPTION_INVALID"
    MODALITY_AMBIGUOUS_UNRESOLVED = "MODALITY_AMBIGUOUS_UNRESOLVED"

    # Bridge gating
    BRIDGE_REQUIRED_MISSING = "BRIDGE_REQUIRED_MISSING"
    BRIDGE_INVALID_CHANNEL_PAIR = "BRIDGE_INVALID_CHANNEL_PAIR"
    BRIDGE_TYPE_UNSUPPORTED = "BRIDGE_TYPE_UNSUPPORTED"
    BRIDGE_U_TO_DNORM_AUTHORITY_MISSING = "BRIDGE_U_TO_DNORM_AUTHORITY_MISSING"
    BRIDGE_U_TO_E_CALIBRATION_MISSING = "BRIDGE_U_TO_E_CALIBRATION_MISSING"
    BRIDGE_CERTIFIED_VALIDATOR_MISSING = "BRIDGE_CERTIFIED_VALIDATOR_MISSING"

    # Scope/time
    SCOPE_JURISDICTION_MISSING = "SCOPE_JURISDICTION_MISSING"
    SCOPE_TIME_MISSING = "SCOPE_TIME_MISSING"
    SCOPE_TIME_INVALID = "SCOPE_TIME_INVALID"

    # Provenance / authority
    PROVENANCE_MISSING = "PROVENANCE_MISSING"
    AUTHORITY_REF_MISSING = "AUTHORITY_REF_MISSING"
    AUTHORITY_REF_UNPARSABLE = "AUTHORITY_REF_UNPARSABLE"
    AUTHORITY_OUT_OF_SCOPE = "AUTHORITY_OUT_OF_SCOPE"

    # Completeness / resolution
    NORM_SUBJECT_MISSING = "NORM_SUBJECT_MISSING"
    NORM_ACTION_MISSING = "NORM_ACTION_MISSING"
    NORM_SCOPE_MISSING = "NORM_SCOPE_MISSING"
    CONDITION_UNDISCHARGED = "CONDITION_UNDISCHARGED"
    DEF_TERM_UNRESOLVED = "DEF_TERM_UNRESOLVED"
    DEF_ENTITY_UNRESOLVED = "DEF_ENTITY_UNRESOLVED"

    # Conflicts / exceptions
    CONFLICT_OBLIGATION_VS_PROHIBITION = "CONFLICT_OBLIGATION_VS_PROHIBITION"
    CONFLICT_OVERLAPPING_SCOPE_UNRESOLVED = "CONFLICT_OVERLAPPING_SCOPE_UNRESOLVED"
    EXCEPTION_ORPHANED = "EXCEPTION_ORPHANED"
    EXCEPTION_PRECEDENCE_UNDETERMINED = "EXCEPTION_PRECEDENCE_UNDETERMINED"

