from __future__ import annotations

from .models import AIBiasMode, ScenarioConfig


SCENARIOS: dict[str, ScenarioConfig] = {
    "healthy_baseline": ScenarioConfig(
        name="healthy_baseline",
        description="Moderate scarcity with decent evidence, decent institutions, and mixed archetypes.",
        scarcity=0.35,
        regeneration_rate=0.12,
        misinformation=0.12,
        verification_capacity=0.62,
        enforcement_capacity=0.65,
        sanction_severity=1.25,
        initial_legitimacy=0.7,
        initial_operativity=0.68,
        sanction_consistency=0.75,
        archive_capacity=0.62,
        appeal_availability=0.75,
        public_epistemics_level=0.62,
        ai_mode=AIBiasMode.NONE,
        ai_reliability=0.0,
    ),
    "weak_e": ScenarioConfig(
        name="weak_e",
        description="Poor evidence quality and high misinformation while formal rules remain unchanged.",
        scarcity=0.35,
        regeneration_rate=0.12,
        misinformation=0.48,
        verification_capacity=0.28,
        enforcement_capacity=0.65,
        sanction_severity=1.25,
        initial_legitimacy=0.7,
        initial_operativity=0.68,
        sanction_consistency=0.75,
        archive_capacity=0.25,
        appeal_availability=0.75,
        public_epistemics_level=0.25,
        ai_mode=AIBiasMode.NONE,
        ai_reliability=0.0,
    ),
    "weak_d": ScenarioConfig(
        name="weak_d",
        description="Norms still exist, but enforcement throughput and consistency are too weak to stay operative.",
        scarcity=0.35,
        regeneration_rate=0.12,
        misinformation=0.12,
        verification_capacity=0.62,
        enforcement_capacity=0.2,
        sanction_severity=0.8,
        initial_legitimacy=0.58,
        initial_operativity=0.32,
        sanction_consistency=0.3,
        archive_capacity=0.62,
        appeal_availability=0.7,
        public_epistemics_level=0.58,
        ai_mode=AIBiasMode.NONE,
        ai_reliability=0.0,
    ),
    "weak_e_weak_d": ScenarioConfig(
        name="weak_e_weak_d",
        description="Poor evidence quality and weak deontic capacity jointly drive collapse and hidden defection.",
        scarcity=0.38,
        regeneration_rate=0.1,
        misinformation=0.52,
        verification_capacity=0.24,
        enforcement_capacity=0.18,
        sanction_severity=0.8,
        initial_legitimacy=0.5,
        initial_operativity=0.28,
        sanction_consistency=0.25,
        archive_capacity=0.22,
        appeal_availability=0.55,
        public_epistemics_level=0.24,
        ai_mode=AIBiasMode.NONE,
        ai_reliability=0.0,
        cooperator_share=0.2,
        opportunist_share=0.45,
        auditor_share=0.1,
        official_share=0.05,
        ai_dependent_share=0.2,
    ),
    "coercive_truth_poor_order": ScenarioConfig(
        name="coercive_truth_poor_order",
        description="Strong sanctions and throughput keep compliance high, but epistemics remain weak and belief quality poor.",
        scarcity=0.34,
        regeneration_rate=0.11,
        misinformation=0.42,
        verification_capacity=0.25,
        enforcement_capacity=0.88,
        sanction_severity=2.4,
        initial_legitimacy=0.48,
        initial_operativity=0.82,
        sanction_consistency=0.84,
        archive_capacity=0.22,
        appeal_availability=0.35,
        public_epistemics_level=0.2,
        ai_mode=AIBiasMode.NONE,
        ai_reliability=0.0,
        cooperator_share=0.16,
        opportunist_share=0.34,
        auditor_share=0.08,
        official_share=0.16,
        ai_dependent_share=0.26,
    ),
    "ai_mediated_epistemics": ScenarioConfig(
        name="ai_mediated_epistemics",
        description="Same society, but public epistemics are mediated by a configurable AI report generator.",
        scarcity=0.35,
        regeneration_rate=0.12,
        misinformation=0.18,
        verification_capacity=0.58,
        enforcement_capacity=0.62,
        sanction_severity=1.25,
        initial_legitimacy=0.67,
        initial_operativity=0.66,
        sanction_consistency=0.72,
        archive_capacity=0.56,
        appeal_availability=0.72,
        public_epistemics_level=0.58,
        ai_mode=AIBiasMode.ACCURATE,
        ai_reliability=0.78,
    ),
}


DEFAULT_SCENARIO_NAME = "healthy_baseline"


def get_scenario(name: str) -> ScenarioConfig:
    return SCENARIOS.get(name, SCENARIOS[DEFAULT_SCENARIO_NAME]).model_copy(deep=True)


def list_scenarios() -> list[ScenarioConfig]:
    return [cfg.model_copy(deep=True) for cfg in SCENARIOS.values()]
